In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

sns.set_style("whitegrid")

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline   
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score ,precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [3]:
from imblearn.over_sampling import SMOTE

In [4]:
df = pd.read_csv("C:/Users/shaik/OneDrive/Desktop/Data science26/DataSetsbyKaggle/smot/Sales - Marketing customer dataset.csv")

In [5]:
df.head()

,customer_id,gender,age,country,city,signup_date,last_purchase_date,acquisition_channel,device_type,subscription_type,...,support_tickets,refund_requested,delivery_delay_days,payment_method,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn
0,10001,Male,52.0,India,Berlin,2022-05-10 00:00:00,2024-12-31 00:00:00,Email,Tablet,Annual,...,0,0,3,UPI,3.0,10,27.56,915.310827,14,0
1,10002,NaN,35.0,Germany,Mumbai,2024-06-16 00:00:00,2024-05-07 00:00:00,Organic,Desktop,Monthly,...,5,0,3,BKash,3.0,7,15.15,2079.960938,11,0
2,10003,Female,27.0,Germany,London,2023-08-23 00:00:00,2024-04-28 00:00:00,Email,Mobile,Annual,...,1,0,2,UPI,5.0,6,13.51,1379.150885,9,0
3,10004,Female,36.0,India,Mumbai,2024-01-28 00:00:00,2023-05-20 00:00:00,Facebook Ads,Tablet,Annual,...,0,0,2,PayPal,4.0,6,25.65,774.652684,7,0
4,10005,Male,29.0,USA,Hamburg,2023-07-21 00:00:00,2024-04-07 00:00:00,Referral,Mobile,Monthly,...,2,1,4,BKash,3.0,1,12.39,87.680409,11,0

In [6]:
df.tail()

,customer_id,gender,age,country,city,signup_date,last_purchase_date,acquisition_channel,device_type,subscription_type,...,support_tickets,refund_requested,delivery_delay_days,payment_method,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn
14995,24996,Female,24.0,UK,New York,2023-10-23 00:00:00,2024-03-02 00:00:00,Referral,Desktop,Monthly,...,3,0,3,UPI,4.0,2,16.96,796.486833,9,0
14996,24997,Male,26.0,Bangladesh,London,2023-01-20 00:00:00,2024-12-03 00:00:00,Google Ads,Mobile,Monthly,...,3,0,2,BKash,NaN,6,23.86,2155.987233,0,0
14997,24998,Male,42.0,USA,Dhaka,2022-10-11 00:00:00,2023-12-04 00:00:00,Organic,Desktop,Monthly,...,3,0,5,UPI,4.0,4,12.55,614.326226,14,0
14998,24999,Female,31.0,UK,Dhaka,2022-04-01 00:00:00,2024-11-11 00:00:00,Facebook Ads,Desktop,Monthly,...,5,1,1,UPI,3.0,1,19.03,849.936622,8,1
14999,25000,Male,23.0,Bangladesh,Berlin,2023-09-20 00:00:00,2024-06-04 00:00:00,Google Ads,Tablet,Annual,...,1,0,2,PayPal,4.0,4,25.86,1393.092943,8,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 15000 non-null  int64
 1   gender                      14262 non-null  str
 2   age                         13800 non-null  float64
 3   country                     15000 non-null  str
 4   city                        15000 non-null  str
 5   signup_date                 15000 non-null  str
 6   last_purchase_date          15000 non-null  str
 7   acquisition_channel         15000 non-null  str
 8   device_type                 15000 non-null  str
 9   subscription_type           15000 non-null  str
 10  is_premium_user             15000 non-null  int64
 11  total_visits                15000 non-null  int64
 12  avg_session_time            15000 non-null  float64
 13  pages_per_session           15000 non-null  float64
 14  email_open_rate             15000 non-null  float64
 15  email_click_rate            15000 non-null  float64
 16  total_spent                 13950 non-null  float64
 17  avg_order_value             15000 non-null  float64
 18  discount_used               15000 non-null  int64
 19  coupon_code                 8867 non-null   str
 20  support_tickets             15000 non-null  int64
 21  refund_requested            15000 non-null  int64
 22  delivery_delay_days         15000 non-null  int64
 23  payment_method              15000 non-null  str
 24  satisfaction_score          14298 non-null  float64
 25  nps_score                   15000 non-null  int64
 26  marketing_spend_per_user    15000 non-null  float64
 27  lifetime_value              15000 non-null  float64
 28  last_3_month_purchase_freq  15000 non-null  int64
 29  churn                       15000 non-null  int64
dtypes: float64(10), int64(10), str(10)
memory usage: 4.6 MB

In [8]:
df.describe()

,customer_id,age,is_premium_user,total_visits,avg_session_time,pages_per_session,email_open_rate,email_click_rate,total_spent,avg_order_value,discount_used,support_tickets,refund_requested,delivery_delay_days,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn
count,15000.000000,13800.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,13950.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,14298.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,17500.500000,35.203913,0.304467,15.000933,8.020805,4.002901,0.496278,0.251231,524.357397,60.080882,0.494467,1.995600,0.147667,2.981333,3.588754,4.968667,17.575238,1235.698200,6.975133,0.153200
std,4330.271354,10.334384,0.460197,3.892704,2.991499,1.479846,0.290108,0.144689,467.050070,24.746203,0.499986,1.421214,0.354781,1.720537,1.088703,3.155495,7.183437,657.521849,4.323443,0.360192
min,10001.000000,-4.000000,0.000000,3.000000,0.006095,0.007845,0.000000,0.000000,0.267291,0.071596,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,5.000000,0.368886,0.000000,0.000000
25%,13750.750000,28.000000,0.000000,12.000000,5.974555,2.989150,0.240000,0.130000,300.432074,43.032470,0.000000,1.000000,0.000000,2.000000,3.000000,2.000000,11.380000,741.301251,3.000000,0.000000
50%,17500.500000,35.000000,0.000000,15.000000,7.991907,3.996992,0.500000,0.250000,498.843859,60.108827,0.000000,2.000000,0.000000,3.000000,4.000000,5.000000,17.630000,1216.210685,7.000000,0.000000
75%,21250.250000,42.000000,1.000000,18.000000,10.059986,5.014406,0.750000,0.380000,702.396635,76.888445,1.000000,3.000000,0.000000,4.000000,4.000000,8.000000,23.770000,1677.860399,11.000000,0.000000
max,25000.000000,95.000000,1.000000,31.000000,19.123716,10.843172,1.000000,0.500000,15910.431879,154.554696,1.000000,9.000000,1.000000,11.000000,5.000000,10.000000,30.000000,3767.490455,14.000000,1.000000

In [9]:
df.shape

(15000, 30)

In [10]:
print("ROWS:", df.shape[0])
print("COLUMNS:", df.shape[1])

ROWS: 15000
COLUMNS: 30

In [11]:
df.describe(include='all')

,customer_id,gender,age,country,city,signup_date,last_purchase_date,acquisition_channel,device_type,subscription_type,...,support_tickets,refund_requested,delivery_delay_days,payment_method,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn
count,15000.000000,14262,13800.000000,15000,15000,15000,15000,15000,15000,15000,...,15000.000000,15000.000000,15000.000000,15000,14298.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
unique,NaN,3,NaN,5,7,1000,800,5,3,2,...,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Male,NaN,Germany,London,2024-09-20 00:00:00,2025-01-17 00:00:00,Organic,Tablet,Monthly,...,NaN,NaN,NaN,UPI,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,6844,NaN,3072,2236,29,32,3055,5043,7666,...,NaN,NaN,NaN,3105,NaN,NaN,NaN,NaN,NaN,NaN
mean,17500.500000,NaN,35.203913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.995600,0.147667,2.981333,NaN,3.588754,4.968667,17.575238,1235.698200,6.975133,0.153200
std,4330.271354,NaN,10.334384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.421214,0.354781,1.720537,NaN,1.088703,3.155495,7.183437,657.521849,4.323443,0.360192
min,10001.000000,NaN,-4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,5.000000,0.368886,0.000000,0.000000
25%,13750.750000,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,0.000000,2.000000,NaN,3.000000,2.000000,11.380000,741.301251,3.000000,0.000000
50%,17500.500000,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.000000,0.000000,3.000000,NaN,4.000000,5.000000,17.630000,1216.210685,7.000000,0.000000
75%,21250.250000,NaN,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,0.000000,4.000000,NaN,4.000000,8.000000,23.770000,1677.860399,11.000000,0.000000
max,25000.000000,NaN,95.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.000000,1.000000,11.000000,NaN,5.000000,10.000000,30.000000,3767.490455,14.000000,1.000000

In [12]:
df.isnull().sum()

customer_id                      0
gender                         738
age                           1200
country                          0
city                             0
signup_date                      0
last_purchase_date               0
acquisition_channel              0
device_type                      0
subscription_type                0
is_premium_user                  0
total_visits                     0
avg_session_time                 0
pages_per_session                0
email_open_rate                  0
email_click_rate                 0
total_spent                   1050
avg_order_value                  0
discount_used                    0
coupon_code                   6133
support_tickets                  0
refund_requested                 0
delivery_delay_days              0
payment_method                   0
satisfaction_score             702
nps_score                        0
marketing_spend_per_user         0
lifetime_value                   0
last_3_month_purchase_freq       0
churn                            0
dtype: int64

In [13]:
numeric_columns = ["age","total_spent","satisfaction_score"]

In [14]:
numeric_columns

['age', 'total_spent', 'satisfaction_score']

In [15]:
for col in numeric_columns:
    df[col ]=df[col].fillna(df[col].median())

In [16]:
df['coupon_code']

0         NEW20
1         NEW20
2           NaN
3           NaN
4           NaN
          ...
14995    SALE15
14996       NaN
14997       NaN
14998       NaN
14999       NaN
Name: coupon_code, Length: 15000, dtype: str

In [17]:
df["coupon_code"] = df["coupon_code"].fillna("No Coupon")

In [18]:
df["gender"]

0          Male
1           NaN
2        Female
3        Female
4          Male
          ...
14995    Female
14996      Male
14997      Male
14998    Female
14999      Male
Name: gender, Length: 15000, dtype: str

In [19]:
df["gender"].value_counts()

gender
Male      6844
Female    6686
Other      732
Name: count, dtype: int64

In [20]:
df["gender"].unique()

<ArrowStringArray>
['Male', nan, 'Female', 'Other']
Length: 4, dtype: str

In [21]:
df["gender"]=df["gender"].fillna("other")

In [22]:
df.isnull().sum()

customer_id                   0
gender                        0
age                           0
country                       0
city                          0
signup_date                   0
last_purchase_date            0
acquisition_channel           0
device_type                   0
subscription_type             0
is_premium_user               0
total_visits                  0
avg_session_time              0
pages_per_session             0
email_open_rate               0
email_click_rate              0
total_spent                   0
avg_order_value               0
discount_used                 0
coupon_code                   0
support_tickets               0
refund_requested              0
delivery_delay_days           0
payment_method                0
satisfaction_score            0
nps_score                     0
marketing_spend_per_user      0
lifetime_value                0
last_3_month_purchase_freq    0
churn                         0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df[df.duplicated()]

Empty DataFrame
Columns: [customer_id, gender, age, country, city, signup_date, last_purchase_date, acquisition_channel, device_type, subscription_type, is_premium_user, total_visits, avg_session_time, pages_per_session, email_open_rate, email_click_rate, total_spent, avg_order_value, discount_used, coupon_code, support_tickets, refund_requested, delivery_delay_days, payment_method, satisfaction_score, nps_score, marketing_spend_per_user, lifetime_value, last_3_month_purchase_freq, churn]
Index: []

[0 rows x 30 columns]

In [25]:
# df.drop_duplicates(inplace=True) agr duplicates ko drop karna ho to ye use kar sakte ho

In [26]:
df.dtypes

customer_id                     int64
gender                            str
age                           float64
country                           str
city                              str
signup_date                       str
last_purchase_date                str
acquisition_channel               str
device_type                       str
subscription_type                 str
is_premium_user                 int64
total_visits                    int64
avg_session_time              float64
pages_per_session             float64
email_open_rate               float64
email_click_rate              float64
total_spent                   float64
avg_order_value               float64
discount_used                   int64
coupon_code                       str
support_tickets                 int64
refund_requested                int64
delivery_delay_days             int64
payment_method                    str
satisfaction_score            float64
nps_score                       int64
marketing_spend_per_user      float64
lifetime_value                float64
last_3_month_purchase_freq      int64
churn                           int64
dtype: object

In [27]:
df["signup_date"]=pd.to_datetime(
    df["signup_date"], 
    errors='coerce',
)

In [28]:
df["last_purchase_date"]=pd.to_datetime(
    df["last_purchase_date"],
    errors='coerce'
)

In [29]:
df[["signup_date","last_purchase_date"]].head()

  signup_date last_purchase_date
0  2022-05-10         2024-12-31
1  2024-06-16         2024-05-07
2  2023-08-23         2024-04-28
3  2024-01-28         2023-05-20
4  2023-07-21         2024-04-07

In [30]:
df.isnull().sum()

customer_id                   0
gender                        0
age                           0
country                       0
city                          0
signup_date                   0
last_purchase_date            0
acquisition_channel           0
device_type                   0
subscription_type             0
is_premium_user               0
total_visits                  0
avg_session_time              0
pages_per_session             0
email_open_rate               0
email_click_rate              0
total_spent                   0
avg_order_value               0
discount_used                 0
coupon_code                   0
support_tickets               0
refund_requested              0
delivery_delay_days           0
payment_method                0
satisfaction_score            0
nps_score                     0
marketing_spend_per_user      0
lifetime_value                0
last_3_month_purchase_freq    0
churn                         0
dtype: int64

In [31]:
df["age"].describe()

count    15000.000000
mean        35.187600
std          9.912519
min         -4.000000
25%         29.000000
50%         35.000000
75%         41.000000
max         95.000000
Name: age, dtype: float64

In [32]:
df["total_spent"].describe()

count    15000.000000
mean       522.571450
std        450.452690
min          0.267291
25%        317.255562
50%        498.843859
75%        683.781508
max      15910.431879
Name: total_spent, dtype: float64

In [33]:
df["total_visits"].describe()

count    15000.000000
mean        15.000933
std          3.892704
min          3.000000
25%         12.000000
50%         15.000000
75%         18.000000
max         31.000000
Name: total_visits, dtype: float64

In [40]:

def detect_outliers_irq(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = data[(data[column] < lower) | (data[column] > upper)]

    print("column:", column)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("lower:", lower)
    print("upper:", upper)
    print("outliers:", len(outliers))
    return outliers

In [41]:
age_outliers = detect_outliers_irq(df, "age")

column: age
Q1: 29.0
Q3: 41.0
IQR: 12.0
lower: 11.0
upper: 59.0
outliers: 218

In [45]:
spent_outliers = detect_outliers_irq(df, "total_spent")

column: total_spent
Q1: 317.255561908933
Q3: 683.7815083157315
IQR: 366.5259464067985
lower: -232.53335770126472
upper: 1233.5704279259292
outliers: 119

In [46]:
visits_outliers = detect_outliers_irq(df, "total_visits")

column: total_visits
Q1: 12.0
Q3: 18.0
IQR: 6.0
lower: 3.0
upper: 27.0
outliers: 39

handle outliers - capping

In [44]:
def cap_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    data[column] = (data[column].clip(lower, upper))

In [47]:
cap_outliers(df, "age")

In [48]:
cap_outliers(df, "total_spent")

In [49]:
cap_outliers(df, "total_visits")

string cleaning

In [50]:
df.select_dtypes(include=['object']).columns

Index(['gender', 'country', 'city', 'acquisition_channel', 'device_type',
       'subscription_type', 'coupon_code', 'payment_method'],
      dtype='str')

In [52]:
df.dtypes

customer_id                            int64
gender                                   str
age                                  float64
country                                  str
city                                     str
signup_date                   datetime64[us]
last_purchase_date            datetime64[us]
acquisition_channel                      str
device_type                              str
subscription_type                        str
is_premium_user                        int64
total_visits                           int64
avg_session_time                     float64
pages_per_session                    float64
email_open_rate                      float64
email_click_rate                     float64
total_spent                          float64
avg_order_value                      float64
discount_used                          int64
coupon_code                              str
support_tickets                        int64
refund_requested                       int64
delivery_delay_days                    int64
payment_method                           str
satisfaction_score                   float64
nps_score                              int64
marketing_spend_per_user             float64
lifetime_value                       float64
last_3_month_purchase_freq             int64
churn                                  int64
dtype: object

In [55]:
string_columns =df.select_dtypes(include=['object']).columns

In [57]:
string_columns

Index(['gender', 'country', 'city', 'acquisition_channel', 'device_type',
       'subscription_type', 'coupon_code', 'payment_method'],
      dtype='str')

In [58]:
for col in string_columns:
    df[col]=(df[col].astype(str).str.strip())

In [64]:
df["gender"].nunique()

3

In [60]:
df["gender"]=(df["gender"].str.title())

In [61]:
df["country"]

0             India
1           Germany
2           Germany
3             India
4               USA
            ...
14995            UK
14996    Bangladesh
14997           USA
14998            UK
14999    Bangladesh
Name: country, Length: 15000, dtype: str

In [65]:
df["country"].unique()

<ArrowStringArray>
['India', 'Germany', 'USA', 'UK', 'Bangladesh']
Length: 5, dtype: str

In [66]:
df["country"]=df["country"].str.title()

In [67]:
df["payment_method"].unique()

<ArrowStringArray>
['UPI', 'BKash', 'PayPal', 'SEPA', 'Card']
Length: 5, dtype: str

In [69]:
df["payment_method"]=(
    df["payment_method"]
    .str.title()
)

In [73]:

for col in [
        "gender",
        "country",
        "acquisition_channel",
        "device_type",
        "subscription_type"
    ]:
        print("\n", col)
        print(df[col].unique())

 gender
<ArrowStringArray>
['Male', 'Other', 'Female']
Length: 3, dtype: str

 country
<ArrowStringArray>
['India', 'Germany', 'Usa', 'Uk', 'Bangladesh']
Length: 5, dtype: str

 acquisition_channel
<ArrowStringArray>
['Email', 'Organic', 'Facebook Ads', 'Referral', 'Google Ads']
Length: 5, dtype: str

 device_type
<ArrowStringArray>
['Tablet', 'Desktop', 'Mobile']
Length: 3, dtype: str

 subscription_type
<ArrowStringArray>
['Annual', 'Monthly']
Length: 2, dtype: str

DATA TRANSFORMATION

In [75]:
df["signup_year"] = df["signup_date"].dt.year

In [76]:
df

,customer_id,gender,age,country,city,signup_date,last_purchase_date,acquisition_channel,device_type,subscription_type,...,refund_requested,delivery_delay_days,payment_method,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn,signup_year
0,10001,Male,52.0,India,Berlin,2022-05-10,2024-12-31,Email,Tablet,Annual,...,0,3,Upi,3.0,10,27.56,915.310827,14,0,2022
1,10002,Other,35.0,Germany,Mumbai,2024-06-16,2024-05-07,Organic,Desktop,Monthly,...,0,3,Bkash,3.0,7,15.15,2079.960938,11,0,2024
2,10003,Female,27.0,Germany,London,2023-08-23,2024-04-28,Email,Mobile,Annual,...,0,2,Upi,5.0,6,13.51,1379.150885,9,0,2023
3,10004,Female,36.0,India,Mumbai,2024-01-28,2023-05-20,Facebook Ads,Tablet,Annual,...,0,2,Paypal,4.0,6,25.65,774.652684,7,0,2024
4,10005,Male,29.0,Usa,Hamburg,2023-07-21,2024-04-07,Referral,Mobile,Monthly,...,1,4,Bkash,3.0,1,12.39,87.680409,11,0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,24996,Female,24.0,Uk,New York,2023-10-23,2024-03-02,Referral,Desktop,Monthly,...,0,3,Upi,4.0,2,16.96,796.486833,9,0,2023
14996,24997,Male,26.0,Bangladesh,London,2023-01-20,2024-12-03,Google Ads,Mobile,Monthly,...,0,2,Bkash,4.0,6,23.86,2155.987233,0,0,2023
14997,24998,Male,42.0,Usa,Dhaka,2022-10-11,2023-12-04,Organic,Desktop,Monthly,...,0,5,Upi,4.0,4,12.55,614.326226,14,0,2022
14998,24999,Female,31.0,Uk,Dhaka,2022-04-01,2024-11-11,Facebook Ads,Desktop,Monthly,...,1,1,Upi,3.0,1,19.03,849.936622,8,1,2022
14999,25000,Male,23.0,Bangladesh,Berlin,2023-09-20,2024-06-04,Google Ads,Tablet,Annual,...,0,2,Paypal,4.0,4,25.86,1393.092943,8,0,2023

In [77]:
df["sign_month"]=(df["signup_date"].dt.month)

In [79]:
df["signup_date"]=(df["signup_month"].dt.month)

KeyError: 'signup_month'

In [ ]:
df["customer_tenure_days"]=df

In [82]:
reference_date =df["last_purchase_date"].max()

In [ ]:
reference_date