In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [32]:
sns.set_theme(style="whitegrid")
print("libraries imported successfully")

libraries imported successfully

In [33]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

In [34]:
url

'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

In [35]:
df = pd.read_csv(url , sep=";")

In [36]:
before = len(df)

In [37]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [39]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [40]:
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [41]:
df.shape

(1599, 12)

In [42]:
df01=df.sample(20,random_state=42)

In [43]:
df01

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
803,7.7,0.560,0.08,2.50,0.114,14.0,46.0,0.99710,3.24,0.66,9.60,6
124,7.8,0.500,0.17,1.60,0.082,21.0,102.0,0.99600,3.39,0.48,9.50,5
350,10.7,0.670,0.22,2.70,0.107,17.0,34.0,1.00040,3.28,0.98,9.90,6
682,8.5,0.460,0.31,2.25,0.078,32.0,58.0,0.99800,3.33,0.54,9.80,5
1326,6.7,0.460,0.24,1.70,0.077,18.0,34.0,0.99480,3.39,0.60,10.60,6
976,7.2,0.410,0.30,2.10,0.083,35.0,72.0,0.99700,3.44,0.52,9.40,5
1493,7.7,0.540,0.26,1.90,0.089,23.0,147.0,0.99636,3.26,0.59,9.70,5
706,7.0,0.780,0.08,2.00,0.093,10.0,19.0,0.99560,3.40,0.47,10.00,5
613,8.2,0.390,0.38,1.50,0.058,10.0,29.0,0.99620,3.26,0.74,9.80,5
1587,5.8,0.610,0.11,1.80,0.066,18.0,28.0,0.99483,3.55,0.66,10.90,6
513,10.5,0.510,0.64,2.40,0.107,6.0,15.0,0.99730,3.09,0.66,11.80,7
1505,6.7,0.760,0.02,1.80,0.078,6.0,12.0,0.99600,3.55,0.63,9.95,3
1525,6.7,0.480,0.08,2.10,0.064,18.0,34.0,0.99552,3.33,0.64,9.70,5
1568,7.0,0.560,0.13,1.60,0.077,25.0,42.0,0.99629,3.34,0.59,9.20,5
220,7.8,0.340,0.37,2.00,0.082,24.0,58.0,0.99640,3.34,0.59,9.40,6
1010,8.9,0.280,0.45,1.70,0.067,7.0,12.0,0.99354,3.25,0.55,12.30,7
30,6.7,0.675,0.07,2.40,0.089,17.0,82.0,0.99580,3.35,0.54,10.10,5
942,10.1,0.430,0.40,2.60,0.092,13.0,52.0,0.99834,3.22,0.64,10.00,7
481,9.4,0.300,0.56,2.80,0.080,6.0,17.0,0.99640,3.15,0.92,11.70,8
135,8.4,0.745,0.11,1.90,0.090,16.0,63.0,0.99650,3.19,0.82,9.60,5

In [44]:
print("rows:",df.shape[1])
print("coloumns:",df.shape[0])

rows: 12
coloumns: 1599

In [45]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [46]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

 data qaulity

In [47]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [48]:
mp=df.isnull().mean()*100
mp

fixed acidity           0.0
volatile acidity        0.0
citric acid             0.0
residual sugar          0.0
chlorides               0.0
free sulfur dioxide     0.0
total sulfur dioxide    0.0
density                 0.0
pH                      0.0
sulphates               0.0
alcohol                 0.0
quality                 0.0
dtype: float64

In [49]:
df.duplicated().sum()

np.int64(240)

In [50]:
df[df.duplicated()]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4,7.4,0.700,0.00,1.90,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
11,7.5,0.500,0.36,6.10,0.071,17.0,102.0,0.99780,3.35,0.80,10.5,5
27,7.9,0.430,0.21,1.60,0.106,10.0,37.0,0.99660,3.17,0.91,9.5,5
40,7.3,0.450,0.36,5.90,0.074,12.0,87.0,0.99780,3.33,0.83,10.5,5
65,7.2,0.725,0.05,4.65,0.086,4.0,11.0,0.99620,3.41,0.39,10.9,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1563,7.2,0.695,0.13,2.00,0.076,12.0,20.0,0.99546,3.29,0.54,10.1,5
1564,7.2,0.695,0.13,2.00,0.076,12.0,20.0,0.99546,3.29,0.54,10.1,5
1567,7.2,0.695,0.13,2.00,0.076,12.0,20.0,0.99546,3.29,0.54,10.1,5
1581,6.2,0.560,0.09,1.70,0.053,24.0,32.0,0.99402,3.54,0.60,11.3,5
1596,6.3,0.510,0.13,2.30,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6

data cleaning

In [51]:
df.columns=(
    df.columns.str.strip().str.lower().str.replace("","_")
)

In [52]:
df.columns

Index(['_f_i_x_e_d_ _a_c_i_d_i_t_y_', '_v_o_l_a_t_i_l_e_ _a_c_i_d_i_t_y_',
       '_c_i_t_r_i_c_ _a_c_i_d_', '_r_e_s_i_d_u_a_l_ _s_u_g_a_r_',
       '_c_h_l_o_r_i_d_e_s_', '_f_r_e_e_ _s_u_l_f_u_r_ _d_i_o_x_i_d_e_',
       '_t_o_t_a_l_ _s_u_l_f_u_r_ _d_i_o_x_i_d_e_', '_d_e_n_s_i_t_y_', '_p_h_',
       '_s_u_l_p_h_a_t_e_s_', '_a_l_c_o_h_o_l_', '_q_u_a_l_i_t_y_'],
      dtype='str')

In [53]:
df = df.drop_duplicates().reset_index(drop=True)

In [54]:
after =len(df)

In [55]:
print("rows before:",before)
print("rows after:",after)
print("duplicates removes:",before - after)

rows before: 1599
rows after: 1359
duplicates removes: 240

In [57]:
df.columns=(
    df.columns.str.strip().str.lower().str.replace("","_")
)

In [59]:
df["___q___u___a___l___i___t___y___"]

0       5
1       5
2       5
3       6
4       5
       ..
1354    6
1355    5
1356    6
1357    5
1358    6
Name: ___q___u___a___l___i___t___y___, Length: 1359, dtype: int64

In [60]:
print("MAXIMUM QUALITY :",df["___q___u___a___l___i___t___y___"].max())
print("MINIMUM QUALITY:",df["___q___u___a___l___i___t___y___"].min())

MAXIMUM QUALITY : 8
MINIMUM QUALITY: 3

In [61]:
df["___q___u___a___l___i___t___y___"].value_counts().sort_index

<bound method Series.sort_index of ___q___u___a___l___i___t___y___
5    577
6    535
7    167
4     53
8     17
3     10
Name: count, dtype: int64>

In [66]:
print("MAXIMUM QUALITY :",df["___a___l___c___o___h___o___l___"].max())
print("MINIMUM QUALITY:",df["___a___l___c___o___h___o___l___"].min())

MAXIMUM QUALITY : 14.9
MINIMUM QUALITY: 8.4

In [67]:
def quality_category(score):
    if score<=4:
        return"low"
    elif score<=6:
        return"medium"
    else:
        return"high"

In [71]:
df["quality_category"] = df["___q___u___a___l___i___t___y___"].apply(quality_category)
df[["___q___u___a___l___i___t___y___", "quality_category"]].head(10)

   ___q___u___a___l___i___t___y___ quality_category
0                                5           medium
1                                5           medium
2                                5           medium
3                                6           medium
4                                5           medium
5                                5           medium
6                                7             high
7                                7             high
8                                5           medium
9                                5           medium

In [72]:
df

,___f___i___x___e___d___ ___a___c___i___d___i___t___y___,___v___o___l___a___t___i___l___e___ ___a___c___i___d___i___t___y___,___c___i___t___r___i___c___ ___a___c___i___d___,___r___e___s___i___d___u___a___l___ ___s___u___g___a___r___,___c___h___l___o___r___i___d___e___s___,___f___r___e___e___ ___s___u___l___f___u___r___ ___d___i___o___x___i___d___e___,___t___o___t___a___l___ ___s___u___l___f___u___r___ ___d___i___o___x___i___d___e___,___d___e___n___s___i___t___y___,___p___h___,___s___u___l___p___h___a___t___e___s___,___a___l___c___o___h___o___l___,___q___u___a___l___i___t___y___,quality_category
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,medium
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,medium
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,medium
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,medium
4,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,medium
1355,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,medium
1356,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,medium
1357,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,medium
1358,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,medium

In [73]:
def Alcohol_cat(value):
    if value<10:
        return"low"
    elif value<12:
        return "M"
    else:
        return"H"

In [75]:
df["Alcohol_cat"]= df["___a___l___c___o___h___o___l___"].apply(Alcohol_cat)

In [76]:
df

,___f___i___x___e___d___ ___a___c___i___d___i___t___y___,___v___o___l___a___t___i___l___e___ ___a___c___i___d___i___t___y___,___c___i___t___r___i___c___ ___a___c___i___d___,___r___e___s___i___d___u___a___l___ ___s___u___g___a___r___,___c___h___l___o___r___i___d___e___s___,___f___r___e___e___ ___s___u___l___f___u___r___ ___d___i___o___x___i___d___e___,___t___o___t___a___l___ ___s___u___l___f___u___r___ ___d___i___o___x___i___d___e___,___d___e___n___s___i___t___y___,___p___h___,___s___u___l___p___h___a___t___e___s___,___a___l___c___o___h___o___l___,___q___u___a___l___i___t___y___,quality_category,Alcohol_cat
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,medium,low
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,medium,low
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,medium,low
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,medium,low
4,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,medium,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1354,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,medium,low
1355,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,medium,M
1356,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,medium,M
1357,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,medium,M
1358,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,medium,M

In [78]:
df["acidity_ratio"] = df["___f___i___x___e___d___ ___a___c___i___d___i___t___y___"] / (df["___v___o___l___a___t___i___l___e___ ___a___c___i___d___i___t___y___"] + 0.0021)

In [80]:
df["free_sulfur_ratio"] = (df["___f___r___e___e___ ___s___u___l___f___u___r___ ___d___i___o___x___i___d___e___"] / (df["___t___o___t___a___l___ ___s___u___l___f___u___r___ ___d___i___o___x___i___d___e___"] + 0.001))

In [81]:
df["___r___e___s___i___d___u___a___l___ ___s___u___g___a___r___"].unique()

array([ 1.9 ,  2.6 ,  2.3 ,  1.8 ,  1.6 ,  1.2 ,  2.  ,  6.1 ,  3.8 ,
        3.9 ,  1.7 ,  4.4 ,  2.4 ,  1.4 ,  2.5 , 10.7 ,  5.5 ,  2.1 ,
        1.5 ,  5.9 ,  2.8 ,  2.2 ,  3.  ,  3.4 ,  5.1 ,  4.65,  1.3 ,
        7.3 ,  7.2 ,  2.9 ,  2.7 ,  5.6 ,  3.1 ,  3.2 ,  3.3 ,  3.6 ,
        4.  ,  7.  ,  6.4 ,  3.5 , 11.  ,  3.65,  4.5 ,  4.8 ,  2.95,
        5.8 ,  6.2 ,  4.2 ,  7.9 ,  3.7 ,  6.7 ,  6.6 ,  2.15,  5.2 ,
        2.55, 15.5 ,  4.1 ,  8.3 ,  6.55,  4.6 ,  4.3 ,  5.15,  6.3 ,
        6.  ,  8.6 ,  7.5 ,  2.25,  4.25,  2.85,  3.45,  2.35,  2.65,
        9.  ,  8.8 ,  5.  ,  1.65,  2.05,  0.9 ,  8.9 ,  8.1 ,  4.7 ,
        1.75,  7.8 , 12.9 , 13.4 ,  5.4 , 15.4 ,  3.75, 13.8 ,  5.7 ,
       13.9 ])

In [82]:
def sagur_cat(value):
    if value<2:
        return"L"
    elif value<5:
        return"M"
    else:
        return "H"

In [ ]:
df{"quality"}